test

diff --git a/tmux/install b/tmux/install
--- a/tmux/install
+++ b/tmux/install
@@ -1,23 +1,31 @@
 #!/bin/bash
 
 # Clone oh my tmux
-if [ -d ~/.tmux]; then
-	echo "~/.tmux already exists, skipping clone."
+if [ -d ~/.tmux ]; then
+	echo "$HOME/.tmux already exists, skipping clone."
 else
 	git clone --single-branch https://github.com/gpakosz/.tmux.git ~/.tmux
 fi
 
-# Create alias of config file
-if [ -e ~/.tmux.conf]; then
-	echo "~/.tmux.conf already exists, aborting."
-	exit 1
+# Create aliases for config files
+if [ -e ~/.tmux.conf ]; then
+	echo "$HOME/.tmux.conf already exists, aborting."
 else
 	ln -s ~/.tmux/.tmux.conf ~/.tmux.conf
 fi
 
-if [ -e ~/.tmux.conf.local]; then
-	echo "~/.tmux.conf.local already exists, aborting."
-	exit 1
+if [ -e ~/.tmux.conf.local ]; then
+	echo "$HOME/.tmux.conf.local already exists, aborting."
 else
 	ln -s ~/dotfiles/tmux/tmux.conf.local ~/.tmux.conf.local
+fi
+
+# Install catppuccin plugin and then cyberdream theme on top
+if [ -e ~/.config/tmux/plugins/catppuccin ]; then
+	echo "$HOME~/.config/tmux/plugins/catppuccin already exists, aborting."
+	exit 1
+else
+	mkdir -p ~/.config/tmux/plugins/catppuccin
+	git clone -b v2.1.3 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
+	cp ./cyberdream-light.conf ~/.config/tmux/plugins/catppuccin/tmux/themes/catppuccin_cyberdream_tmux.conf
 fi
